<template>
  <div>
    <md-table v-model="users" :table-header-color="tableHeaderColor">
      <md-table-row slot="md-table-row" slot-scope="{ item }">
        <md-table-cell md-label="ID">{{ item.id }}</md-table-cell>
        <md-table-cell md-label="Vorname">{{ item.prename }}</md-table-cell>
        <md-table-cell md-label="Nachname">{{ item.surname }}</md-table-cell>
        <md-table-cell md-label="Klasse">{{ item.class_title }}</md-table-cell>
      </md-table-row>
    </md-table>
  </div>
</template>

<script>
export default {
  name: "ordered-table",
  props: {
    tableHeaderColor: {
      type: String,
      default: ""
    }
  },
  data() {
    return {
      selected: [],
      users: [
         { id: 160,
        prename: 'Martin',
        surname: 'Grunewald',
        class_id: 3,
        class_title: '3c',
        course_title: 'Deutsch',
        course_id: 72,
        teacher_prename: 'Marco',
        teacher_surname: 'Traugott' },
      { id: 162,
        prename: 'Uwe',
        surname: 'Gersten',
        class_id: 3,
        class_title: '3c',
        course_title: 'Deutsch',
        course_id: 72,
        teacher_prename: 'Marco',
        teacher_surname: 'Traugott' },
      { id: 163,
        prename: 'Robert',
        surname: 'Bieber',
        class_id: 4,
        class_title: '4z',
        course_title: 'Deutsch',
        course_id: 75,
        teacher_prename: 'Max',
        teacher_surname: 'Vogel' },
      { id: 164,
        prename: 'Jürgen',
        surname: 'Drescher',
        class_id: 2,
        class_title: '2b',
        course_title: 'Deutsch',
        course_id: 64,
        teacher_prename: 'Juliane',
        teacher_surname: 'Braun' },
      { id: 167,
        prename: 'Lucas',
        surname: 'Shuster',
        class_id: 4,
        class_title: '4z',
        course_title: 'Deutsch',
        course_id: 75,
        teacher_prename: 'Max',
        teacher_surname: 'Vogel' },
      { id: 169,
        prename: 'Martin',
        surname: 'Freeh',
        class_id: 4,
        class_title: '4z',
        course_title: 'Deutsch',
        course_id: 75,
        teacher_prename: 'Max',
        teacher_surname: 'Vogel' },
      { id: 172,
        prename: 'Doreen',
        surname: 'Bar',
        class_id: 3,
        class_title: '3c',
        course_title: 'Deutsch',
        course_id: 72,
        teacher_prename: 'Marco',
        teacher_surname: 'Traugott' },
      { id: 174,
        prename: 'Frank',
        surname: 'Ziegler',
        class_id: 1,
        class_title: '1a',
        course_title: 'Deutsch',
        course_id: 59,
        teacher_prename: 'Uwe',
        teacher_surname: 'Bader' },
      { id: 177,
        prename: 'Mario',
        surname: 'Beike',
        class_id: 4,
        class_title: '4z',
        course_title: 'Deutsch',
        course_id: 75,
        teacher_prename: 'Max',
        teacher_surname: 'Vogel' },
      { id: 179,
        prename: 'Marco',
        surname: 'Diederich',
        class_id: 2,
        class_title: '2b',
        course_title: 'Deutsch',
        course_id: 64,
        teacher_prename: 'Juliane',
        teacher_surname: 'Braun' },
      { id: 182,
        prename: 'Barbara',
        surname: 'Baumgaertner',
        class_id: 3,
        class_title: '3c',
        course_title: 'Deutsch',
        course_id: 72,
        teacher_prename: 'Marco',
        teacher_surname: 'Traugott' },
      { id: 183,
        prename: 'Felix',
        surname: 'Freitag',
        class_id: 3,
        class_title: '3c',
        course_title: 'Deutsch',
        course_id: 72,
        teacher_prename: 'Marco',
        teacher_surname: 'Traugott' },
      { id: 187,
        prename: 'Sara',
        surname: 'Feierabend',
        class_id: 3,
        class_title: '3c',
        course_title: 'Deutsch',
        course_id: 72,
        teacher_prename: 'Marco',
        teacher_surname: 'Traugott' },
      { id: 188,
        prename: 'Lena',
        surname: 'Propst',
        class_id: 3,
        class_title: '3c',
        course_title: 'Deutsch',
        course_id: 72,
        teacher_prename: 'Marco',
        teacher_surname: 'Traugott' },
      { id: 197,
        prename: 'Ursula',
        surname: 'Nagel',
        class_id: 2,
        class_title: '2b',
        course_title: 'Deutsch',
        course_id: 64,
        teacher_prename: 'Juliane',
        teacher_surname: 'Braun' },
      { id: 198,
        prename: 'Lea',
        surname: 'Faust',
        class_id: 3,
        class_title: '3c',
        course_title: 'Deutsch',
        course_id: 72,
        teacher_prename: 'Marco',
        teacher_surname: 'Traugott' }
      ]
    };
  }
};
</script>
